apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: prometheus-operator-admission-webhook
    app.kubernetes.io/part-of: rhobs-prometheus-operator
    app.kubernetes.io/version: 0.64.1-rhobs4
  name: rhobs-prometheus-operator-admission-webhook
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    app.kubernetes.io/name: prometheus-operator-admission-webhook
    app.kubernetes.io/part-of: rhobs-prometheus-operator
status:
  loadBalancer: {}
