apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/name: prometheus-operator-admission-webhook
  name: alertmanagerconfigs.monitoring.rhobs
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    # NOTE: the caBundle get automatically injected by OLM
    caBundle: Cg==
    service:
      # NOTE: when changing the service, ensure the same changes are applied
      # to prometheus-rule-validating-webhook
      name: rhobs-prometheus-operator-admission-webhook
      namespace: openshift-operators
      path: /admission-alertmanagerconfigs/validate
  name: alertmanagerconfigs.monitoring.rhobs
  failurePolicy: Ignore
  rules:
  - apiGroups:
    - monitoring.rhobs
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - alertmanagerconfigs
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 5
