apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/name: rhobs-prometheus-operator-admission-webhook
  name: prometheusrules.monitoring.rhobs
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    # NOTE: the caBundle get automatically injected by OLM
    caBundle: Cg==
    service:
      # NOTE: when changing the service, ensure the same changes are applied
      # to alertmanager-config-validating-webhook as well
      name: rhobs-prometheus-operator-admission-webhook
      namespace: operators
      path: /admission-prometheusrules/validate
  failurePolicy: Ignore
  name: prometheusrules.monitoring.rhobs
  rules:
  - apiGroups:
    - monitoring.rhobs
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - prometheusrules
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 5
