# The workflow create a git tag and publishes container images
name: release
on:
  push:
    branches:
      - 'rhobs-rel-*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore(release):')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PUSH_TOKEN }}

      - name: Import common environment variables
        run: cat ".github/env" >> $GITHUB_ENV

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '${{ env.golang-version }}'

      - name: login to quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.quay_repo_username }}
          password: ${{ secrets.quay_repo_password }}

      - name: Publish tag
        id: git_tag
        run: |
          version="$(head -1 VERSION)"
          git config user.name rhobs-release-bot
          git config user.email release-bot@monitoring.rhobs.io

          git tag -a "v${version}" -m "v${version}"
          git tag -a "pkg/apis/monitoring/v${version}" -m "v${version}"
          git tag -a "pkg/client/monitoring/v${version}" -m "v${version}"

          git push --follow-tags

      # TODO:  <29-09-22, sthaha> # should we create a release?
      - name: Build RHOBS images and push
        env:
          IMAGE_ORG: ${{ secrets.IMAGE_ORG }}
        run:
          REGISTRIES="quay.io" \
          IMAGE_OPERATOR="$IMAGE_ORG/obo-prometheus-operator" \
          IMAGE_WEBHOOK="$IMAGE_ORG/obo-admission-webhook" \
          IMAGE_RELOADER="$IMAGE_ORG/obo-prometheus-config-reloader" \
          CPU_ARCHS="amd64" \
          ./scripts/push-docker-image.sh

          echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)

          #       - name: Create Github release
          #         uses: actions/create-release@v1
          #         env:
          #           GITHUB_TOKEN: ${{ secrets.REPOSITORY_PUSH_TOKEN }}
          #         with:
          #           release_name: ${{ steps.git_tag.outputs.tag_name }}
          #           tag_name: ${{ steps.git_tag.outputs.tag_name }}
